// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvfhcykdmzuwcmgussar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12ZmhjeWtkbXp1d2NtZ3Vzc2FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMjk3NzksImV4cCI6MjA3MDkwNTc3OX0.kXegy2tPxGB8dVg-mP06B3hgSPJU1tedkhkXpTkgRQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});